### ISSUE TITLE
Wallet Does not show Transactions

### ISSUE THREAD

**Issue by AndroidDev77** [swap-dev/swap-gui#1]
After wallet sync wallet does not show any transactions or balance. Transaction are properly shown on web wallet and in block chain.

-Swap v3.0.2 gui-win
-Windoes 10 64 bit

**Comment by LPHuynh** [comment]
1) re-scan the wallet balance.
2) Make sure the wallet restore height is below the height of your first received transaction
3) delete your wallet cache (it's the large file in your wallet folder without any extension), and allow it to regenerate.

**Comment by Bafff** [comment]
Please check **Wallet restore height** here:
![image](https://user-images.githubusercontent.com/26187677/61395384-fdb88080-a8cd-11e9-8d42-5349916eb3e1.png)

**Comment by AndroidDev77** [comment]
1. ReScanned wallet - No Change
2. Changed Restore height to yesterday (Trans was today) - No Change
3. Deleted Wallet Cache - No Change, but I did lose a wallet address I added in Receive tab.

**Comment by Bafff** [comment]
@AndroidDev77 can you show screenshot of your **Settings -> Info** tab?

**Comment by AndroidDev77** [comment]
![image](https://user-images.githubusercontent.com/2716432/61396561-fbd2cb00-a895-11e9-8c71-bf032a88b336.png)

**Comment by Bafff** [comment]
@AndroidDev77 please use 0 height for now. I 99,9% sure it will work
@LPHuynh I've repited steps, changed restore height to 2 days later, and now "They're gone". I have 0.0 balance but I  have received and sent some coins (much ;) after that block. 
![image](https://user-images.githubusercontent.com/26187677/61396884-5ccbc480-a8d1-11e9-88be-7c44d75b4e7b.png)

Oh wait, I know what's going on....

**Comment by Bafff** [comment]
**1403782** - current block
**1858228** - restored height

I think something is wrong with date to block conversion or it is not there at all (we need to use just block № and not the date?

**Comment by AndroidDev77** [comment]
@Bafff I changed the block height and this worked. That's weird that it defaulted to that restore height.

**Comment by Bafff** [comment]
Use this workaround and we will try to fix that ASAP ;)

Stay with us! ;)

**Comment by Bafff** [comment]
@LPHuynh This height works just fine, for example:
**Wallet creation height: 1303782**

 So the mechanics is ok, just smth wrong with converting date2block

**Comment by AndroidDev77** [comment]
Also, just an fyi some of the remote nodes mentioned in the wiki weren't able to connect
node.swap.fyi:19950
node.xwp.fyi:19950

Node.bitkitten.xyz:18850  however did work

https://github.com/swap-dev/swap/wiki

**Comment by Bafff** [comment]
yeah that's already fixed for new users. Sorry for inconvinence!

**Comment by LPHuynh** [comment]
I am able to replicate and confirm that this is a bug 👌 

Thanks for the report.

**Comment by LPHuynh** [comment]
I'll close this issue in favor of #2, which is the same bug described.
