### ISSUE TITLE
Wallet restore height using date FAILS

### ISSUE THREAD

**Issue by Bafff** [swap-dev/swap-gui#2]
If I use 2019-07-17 as a wallet restore date i see strange behavior

**1403782** - current block
**1858228** - restored height

I think something is wrong with date to block conversion or it is not there at all (we need to use just block № and not the date?

_Originally posted by @Bafff in https://github.com/swap-dev/swap-gui/issues/1#issuecomment-512447005_
P.S. just starting using GH please do not blame me if smth I am doing is wrong

**Comment by LPHuynh** [comment]
This fix will be included in v3.0.3 of the GUI wallet: 55ac5bb4aa320b86cfcee3d14b79f49a576478dc

Thank you for the report 👌

**Comment by Bafff** [comment]
Take five! :)
