### ISSUE TITLE
Node connection

### ISSUE THREAD

**Issue by Bafff** [swap-dev/swap-gui#3]
If I was connected to a  failed node using remote node feature I'll see smth like this:
![image](https://user-images.githubusercontent.com/26187677/61456707-69065f00-a96f-11e9-821f-25e9a2f0a22b.png)

Then I'll restart my wallet, and this would not help. 

**But** if I paste another 1000% working node - nothing would change, I'll still be disconnected.
I will not restart my wallet another time - for what? I have already did that ;)

And I'll go to the support.

But what you need is to **insert working node info AND restart a wallet** (maybe force close it and recheck for hanged swap process

Please **DO NOT** use those nodes for now (temporarly):
node.swap.fyi

Please, **USE** this nodes:
autonode.xwp.fyi
node.pocketwhale.info:19950
node2.pocketwhale.info:19950
node3.pocketwhale.info:19950
node4.pocketwhale.info:19950

**Comment by SPuzo** [comment]
Having the same problems and lost 150 coins because of this wallet can not connecting to the network the next day...

**Comment by SPuzo** [comment]
> If I was connected to a failed node using remote node feature I'll see smth like this:
> ![image](https://user-images.githubusercontent.com/26187677/61456707-69065f00-a96f-11e9-821f-25e9a2f0a22b.png)
> 
> Then I'll restart my wallet, and this would not help.
> 
> **But** if I paste another 1000% working node - nothing would change, I'll still be disconnected.
> I will not restart my wallet another time - for what? I have already did that ;)
> 
> And I'll go to the support.
> 
> But what you need is to **insert working node info AND restart a wallet** (maybe force close it and recheck for hanged swap process
> 
> Please **DO NOT** use those nodes for now (temporarly):
> node.swap.fyi
> node.bitkitten.xyz
> 
> Please, **USE** this nodes:
> 
> node.pocketwhale.info:19950
> node2.pocketwhale.info:19950
> node3.pocketwhale.info:19950
> node4.pocketwhale.info:19950

Having the same problems and lost 150 coins because of this wallet can not connect to the network the next day...

**Comment by Bafff** [comment]
@SPuzo You did not lost anything. Just set up your GUI wallet with a working node and you will see your money.

**Comment by SPuzo** [comment]
> @SPuzo You did not lost anything. Just set up your GUI wallet with a working node and you will see your money.

I did... I redownload a new wallet and there's nothing in there zero balance...

**Comment by pharmecis** [comment]
Tell it to rescan your balance from ZERO.  If your coins are on the block chain, you have not lost your coins.

**Comment by SPuzo** [comment]
> Tell it to rescan your balance from ZERO. If your coins are on the block chain, you have not lost your coins.

This wallet doesn't show rescan or custom nodes for some reason. VER: swap-v3.0.2-gui-win

**Comment by LPHuynh** [comment]
@SPuzo The coins are stored on the blockchain. The GUI wallet only interface with said blockchain. No coins are ever lost as long as it was sent to the correct address that you have access to (i.e. you have the *.keys file, seeds, or private keys).

you set a custom node as in the screenshot provided in the first post.

I'm marking this as a bug (selecting a new node after trying to connect to a downed node crashes the wallet).

**Comment by SPuzo** [comment]
> @SPuzo The coins are stored on the blockchain. The GUI wallet only interface with said blockchain. No coins are ever lost as long as it was sent to the correct address that you have access to (i.e. you have the *.keys file, seeds, or private keys).
> 
> you set a custom node as in the screenshot provided in the first post.
> 
> I'm marking this as a bug (selecting a new node after trying to connect to a downed node crashes the wallet).

I know that "coins are stored on the blockchain" but the wallet from last night I deleted because people in discord gave me the wrong info, so I re-download this new wallet from the website... See screenshot... The wallet last night I had had all of that but this new one doesn't show it...
![swap](https://user-images.githubusercontent.com/53061935/61494822-da98da00-a97c-11e9-982e-56e70963a0ea.JPG)
And no I don't have the keys from the old wallet...

**Comment by LPHuynh** [comment]
you're using the wallet in simple mode, which does automatic node selection.

Your .keys file is located at the wallet path you blocked out. If you didn't delete this directory, then it's still there.

If your wallet address didn't change, then just set the restore height to 0 as @pharmecis suggest to regenerate the wallet cache (which may have gotten corrupted). 

If you need further support please join one of our social media for help. 
This is a bug tracker, not a support forum, and the issue you're describing is unrelated to the issue @Baff reported.

**Comment by SPuzo** [comment]
Ok, I got it back in my delete file thanks!

**Comment by Bafff** [comment]
can we close that?
